### ISSUE TITLE
Maybe add option max_log_lines=3000 to speed up colored painting?

### ISSUE THREAD

**Issue by Alexey-T** [veksha/cuda_exterminal#32]

**Comment by veksha** [comment]
do you think it is slow? i don't see that line count is affecting colored painting.

PS: slow timer (70 ms) can affect responsiveness a little. but i can't set it to 10 ms, because multiple terminals on windows will make Cud appear frozen (when you open Command palette, for example)
As I said before. using timer is not the best choice, I think.

But limit the lines is a nice idea, nevertheless.
